name: 'Sign'
description: 'Sign Unreal Plugin libs'
inputs:
  path:
    description: 'Path to dir with objects which going to be sign'
    required: true
  platform:
    description: 'Define build platform [macos|windows]'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Sign Unreal Plugin
      run: |
        export INPUT_SIGN_PATH=${{ inputs.path }}
        export INPUT_PLATFORM=${{ inputs.platform }}
        security unlock-keychain -p ${DOLBYIO_KEYCHAIN_PASSWORD} ~/Library/Keychains/dolbyio.keychain-db
        python3 ./.github/actions/sign/sign.py
      shell: bash
