name: Check Branch and Trigger Workflow

on:
  push:
    branches:
      - '*'
          # exists=$(curl -s -o /dev/null -w "%{http_code}" -X GET \
          #   "https://api.github.com/repos/millicast/millicast-player-unreal-engine-plugin/git/${{ github.ref }}" \
          # )
jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch exists
        id: branch-check
        run: |
          echo "branch name: ${{ github.ref }}"
          exists=$(curl -s -o /dev/null -w "%{http_code}" -X GET \
            "https://api.github.com/repos/millicast/millicast-player-unreal-engine-plugin/git/${{ github.ref }}" \
          )
          echo "http response(200 - branch exists, 404 - branch doesn't exist): $exists"
          echo "branch_exists=$(if [ $exists -eq 200 ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT 

      - name: Trigger Workflow
        if: steps.branch-check.outputs.branch_exists == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          # token: ${{ secrets.TOKEN }}
          repository: millicast/millicast-player-ue5-example
          event-type: Build_Unreal_Plugin_Example
          ref: ${{ github.ref }}

      - name: Trigger Workflow on Dev Branch
        if: steps.branch-check.outputs.branch_exists == 'false'
        with:
          # token: ${{ secrets.TOKEN }}
          repository: millicast/millicast-player-ue5-example
          event-type: Build_Unreal_Plugin_Example
          ref: dev

