name: Check Branch and Trigger Workflow

on:
  push:
    branches:
      - '*'

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch exists
        id: branch-check
        uses: actions/github-script@v5
        with:
          script: |
            const branchExists = await github.rest.repos.getBranch({
              owner: 'millicast',
              repo: 'millicast-player-unreal-engine-plugin',
              branch: github.context.ref.replace('refs/heads/', ''),
            });
            return branchExists.status === 200;

      # - name: Trigger Workflow
      #   if: steps.branch-check.outputs.branchExists
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     repository: other-repo-owner/other-repo
      #     event-type: workflow-name
      #     ref: ${{ github.ref }}

      # - name: Trigger Workflow on Dev Branch
      #   if: steps.branch-check.outputs.branchExists == 'false'
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     repository: another-repo-owner/another-repo
      #     event-type: workflow-name
      #     ref: dev

      - name: Trigger Workflow
        if: steps.branch-check.outputs.branchExists
        run: |
          echo "branch exists"

      - name: Trigger Workflow on Dev Branch
        if: steps.branch-check.outputs.branchExists == 'false'
        run: |
          echo "branch doesn't exists"

