name: Check Branch and Trigger Workflow

on:
  push:
    branches:
      - '*'

jobs:
  check-branch:
    runs-on: self-hosted

    steps:
      - name: Check if branch exists
        id: branch-check
        run: |
          echo "branch name: ${{ github.ref }}"
          exists=$(curl -s -o /dev/null -w "%{http_code}" -X GET \
            "https://api.github.com/repos/millicast/millicast-player-unreal-engine-plugin/git/${{ github.ref }}" \
          )
          echo "http response(200 - branch exists, 404 - branch doesn't exist): $exists"
          echo "branch_exists=$(if [ $exists -eq 200 ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT 

# rm ${{ github.workspace }}/gh_app_priv_key.pem ${{ github.workspace }}/generate_gh_app_installation_token.py
      - name: generate GH access token
        env: 
          GH_APP_ID: ${{ secrets.GH_TriggerGHActions_APP_ID }}
          GH_APP_INSTALLATION_ID: ${{ secrets.GH_TriggerGHActions_APP_INSTALLATION_ID }}
          REPO: ${{ github.repository }}
        run: |
          python3 -m pip install jwt requests
          echo "${{ vars.GH_APP_TRIGGERGHACTION_TOKEN_PYTHON_SCRIPT }}" | base64 -d > "${{ github.workspace }}/generate_gh_app_installation_token.py"
          echo "${{ secrets.GH_APP_TRIGGERGHACTION_PRIV_KEY }}" > "${{ github.workspace }}/gh_app_priv_key.pem"
          export PEM_FILE="${{ github.workspace }}/gh_app_priv_key.pem"
          export GH_ACCESS_TOKEN_1H_EXPIRATION="$( python3 ${{ github.workspace }}/generate_gh_app_installation_token.py )"
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/actions/secrets/GH_ACCESS_TOKEN_1H_EXPIRATION" \
            -d "{\"encrypted_value\":\"$(echo -n "$GH_ACCESS_TOKEN_1H_EXPIRATION" | base64)\"}"
          echo "Secret created successfully."

          
    
      - name: Trigger Workflow
        if: steps.branch-check.outputs.branch_exists == 'true'
        run: |
          echo "trigger Workflow"


      - name: Trigger Workflow on Dev Branch
        if: steps.branch-check.outputs.branch_exists == 'false'
        run: |
          echo "trigger default workflow"

