name: Check Branch and Trigger Workflow

on:
  push:
    branches:
      - '*'

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch exists
        id: branch-check
        run: |
          echo "${{ github.ref }}"
          exists=$(curl -s -o /dev/null -w "%{http_code}" -X GET \
            "https://api.github.com/repos/millicast/millicast-player-unreal-engine-plugin/git/${{ github.ref }}" \
          )
          echo "$exists"
          echo "branch_exists=$(if [ $exists -eq 200 ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT 

      # - name: Trigger Workflow
      #   if: steps.branch-check.outputs.branchExists
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     repository: other-repo-owner/other-repo
      #     event-type: workflow-name
      #     ref: ${{ github.ref }}

      # - name: Trigger Workflow on Dev Branch
      #   if: steps.branch-check.outputs.branchExists == 'false'
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.TOKEN }}
      #     repository: another-repo-owner/another-repo
      #     event-type: workflow-name
      #     ref: dev

      - name: Trigger Workflow
        if: steps.branch-check.outputs.branch_exists == 'true'
        run: |
          echo "branch exists"

      - name: Trigger Workflow on Dev Branch
        if: steps.branch-check.outputs.branch_exists == 'false'
        run: |
          echo "branch doesn't exists"

